<a href="https://colab.research.google.com/github/rauttanushka69-lgtm/Python-Basic-Projects./blob/master/Task20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv('ford.csv')
X = df.drop('price', axis=1)
y = df['price']
print(X.shape)
print(y.shape)

(17966, 8)
(17966,)

In [ ]:
cat_cols = X.select_dtypes(include='object').columns
X_encoded = pd.get_dummies(X, columns=cat_cols, drop_first=True)
X_encoded = X_encoded.astype(int)
X_encoded.head()

,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
num_cols = ['year', 'mileage', 'tax', 'mpg', 'engineSize']
scaler = StandardScaler()
X_encoded[num_cols] = scaler.fit_transform(X_encoded[num_cols])
X_encoded[num_cols].head()

       year   mileage       tax       mpg  engineSize
0  0.065128 -0.380998  0.591358 -0.042122   -0.447984
1  0.552866 -0.733359  0.591358 -0.042122   -0.447984
2  0.065128 -0.560132  0.591358 -0.042122   -0.447984
3  1.040605 -0.662640  0.510727 -1.721198   -0.447984
4  1.040605 -1.123724  0.510727 -0.931045   -0.447984

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.33, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12037, 34)
(5929, 34)
(12037,)
(5929,)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
print(model.intercept_)
print(model.coef_)

11607.732472620928
[ 2.03726418e+03 -1.31955378e+03 -2.12184657e+01 -9.89026938e+02
  8.79613637e+02  9.71814865e+02  1.28894775e+03  8.45385559e+03
  1.38974407e+04  9.26481966e+02  3.01804524e+03  3.49070772e+03
  5.69209998e+03  1.23826482e+03  4.01599584e+03 -4.41428233e+02
 -2.90977342e+03  3.22843740e+03  2.42053593e+03  1.30231240e+04
  7.21950570e+03  7.04858394e-12  5.53585973e+03  4.54747351e-13
  3.42681639e+03  5.55272266e+03  8.70595935e+02 -5.68441064e+02
 -5.08708628e+02 -2.47765213e+02  0.00000000e+00  8.64612222e+03
  6.57660484e+02 -1.29974914e+03]

In [ ]:
r2 = r2_score(y_test, y_pred)
print(r2)
print("""R2 score tells how much % of price variation model explains.
If R2 = 0.85 then model explains 85% variation.
Higher R2 means better performance.""")

0.8396626991294073
R2 score tells how much % of price variation model explains.
If R2 = 0.85 then model explains 85% variation.
Higher R2 means better performance.

In [ ]:
joblib.dump(model, 'LR_ford_car.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(list(X_encoded.columns), 'columns.pkl')

['columns.pkl']

In [13]:
import joblib

joblib.dump(model, 'LR_ford_car.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(list(X_encoded.columns), 'columns.pkl')

print("Model Saved Successfully")
print("Files created: LR_ford_car.pkl, scaler.pkl, columns.pkl")

Model Saved Successfully
Files created: LR_ford_car.pkl, scaler.pkl, columns.pkl